---

# Network provider:
ansible_connection: network_cli
ansible_network_os: nxos
ansible_user: "{{ hostvars[inventory_hostname]['nxos_user'] | default('admin') }}"
ansible_ssh_pass: "{{ hostvars[inventory_hostname]['nxos_password'] | default('') }}"