---

- hosts: Campus
# Prompt for Username and Password #
  vars_prompt:
    - name: IOS_User_Prompt
      prompt: "Enter Cisco IOS Username"
      private: no 
    - name: IOS_Password_Prompt
      prompt: "Enter IOS Password"
      private: yes      
  tasks:
# Register Username and Password #
    - set_fact:   
        ios_user: "{{ IOS_User_Prompt }}"     
        ios_password: "{{ IOS_Password_Prompt }}"
      no_log: true
      delegate_to: localhost
      run_once: true     
  tasks:
# Gather Ansible Facts About Core Access Lists #
    - name: show access-lists
      ios_command:
        commands:
          - show access-lists
      register: all_access_lists_raw

# Genie Parse command #
    - name: Set Fact Genie Filter 
      set_fact:
        pyats_all_access_lists: "{{ all_access_lists_raw['stdout'][0] | parse_genie(command='show access-lists', os='ios') }}"

# Create Nice JSON, Nice YAML Files #
# Create JSON file with Ansible Facts #
    - name: Create raw JSON file
      copy: 
        content: | 
          {{ pyats_all_access_lists | to_nice_json }}
        dest: ../FACTS/IOS/{{ inventory_hostname }}/Show_ACL.json

# Create YAML file with Ansible Facts #
    - name: Create raw YAML
      copy: 
        content: | 
          {{ pyats_all_access_lists | to_nice_yaml }}
        dest: ../FACTS/IOS/{{ inventory_hostname }}/Show_ACL.yml

# Add Headers to YAML #
    - name: Header Row
      lineinfile:
        path: ../FACTS/IOS/{{ inventory_hostname }}/Show_ACL.yml
        insertbefore: BOF
        line: ---        
      delegate_to: localhost

# Create CSV and MD File #
# Create MAC CSV and MD file with results #
    - name: CSV and MD using Jinja templates
      template:
        src: ../templates/ios/ACLFacts.j2
        dest: ../FACTS/IOS/{{ inventory_hostname }}/Show_ACL.{{ item }}
      loop: 
        - csv
        - md

# Create Mind Map # 
    - name: create IP Access-List Mind Map 
      shell: "markmap --no-open ../FACTS/IOS/{{ inventory_hostname }}/Show_ACL.md -o ../FACTS/IOS/{{ inventory_hostname }}/Show_ACL.html"
      register: markmap  