---

- hosts: DC
  vars_prompt:
    - name: NXOS_User_Prompt
      prompt: "Enter Cisco NXOS Username"
      private: no 
    - name: NXOS_Password_Prompt
      prompt: "Enter Cisco NXOS Password"
      private: yes      
  tasks:
# Register Username and Password #
    - set_fact:   
        nxos_user: "{{ NXOS_User_Prompt }}"     
        nxos_password: "{{ NXOS_Password_Prompt }}"
      no_log: true
      delegate_to: localhost
      run_once: true   
  tasks:
# Run show mac address-table and register results #
    - name: show mac address-table 
      nxos_command:
        commands:
          - show mac address-table
      register: mac_table_raw

# Genie parse command #
    - name: Set Fact Genie Filter - show mac address-table
      set_fact:
        pyats_mac_table: "{{ mac_table_raw.stdout[0] | parse_genie(command='show mac address-table', os='nxos', platform='n7k') }}"

# Create Nice JSON, Nice YAML Files #
# Create JSON file with Ansible Facts #
    - name: Create raw JSON file
      copy: 
        content: | 
          {{ pyats_mac_table | to_nice_json }}
        dest: ../FACTS/NXOS/{{ inventory_hostname }}/Show_MAC.json

# Create YAML file with Ansible Facts #
    - name: Create raw YAML
      copy: 
        content: | 
          {{ pyats_mac_table | to_nice_yaml }}
        dest: ../FACTS/NXOS/{{ inventory_hostname }}/Show_MAC.yml

# Add Headers to YAML #
    - name: Header Row
      lineinfile:
        path: ../FACTS/NXOS/{{ inventory_hostname }}/Show_MAC.yml
        insertbefore: BOF
        line: ---        
      delegate_to: localhost    

# Create CSV and MD File #
# Create MAC CSV and MD file with results #
    - name: CSV and MD using Jinja templates
      template:
        src: ../templates/nxos/MACFacts.j2
        dest: ../FACTS/NXOS/{{ inventory_hostname }}/Show_MAC.{{ item }}
      loop: 
        - csv
        - md

# Create Mind Map # 
    - name: create Core Facts Mind Map 
      shell: "markmap --no-open ../FACTS/NXOS/{{ inventory_hostname }}/Show_MAC.md -o ../FACTS/NXOS/{{ inventory_hostname }}/Show_MAC.html"
      register: markmap
      delegate_to: localhost